default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fitness_for_hackers_dev

test:
  <<: *default
  database: fitness_for_hackers_test

production:
  <<: *default
  database: fitness_for_hackers_prod
